\documentclass[10pt]{article}
\usepackage[margin=1.0in]{geometry}
\usepackage[utf8]{inputenc}
\usepackage[parfill]{parskip}
\usepackage{hyperref}
\usepackage{natbib}
\SweaveOpts{keep.source=TRUE} 

\title{POD Vignette}
\author{Daniel Bottomly}
%\VignetteIndexEntry{pod}
\begin{document}

\maketitle

\section{Introduction}

This package implements the outlier detection methods from \citep{bottomly2013}.  Specifically it implements the outlying degree approaches, Zscore and Rscore described in that paper and makes them conveniently available either for basic matrices or expression-specific classes such as the \texttt{ExpressionSet}.

First, read in the data using an appropriate package from the Bioconductor project \url{http://bioconductor.org} such as \texttt{oligo}, \texttt{affy} or \texttt{XPS}.  The resulting object from those packages should be an \texttt{Expression set}.   For the purposes of this vignette we will use a simulated dataset bundled with the package.

<<eval=TRUE, echo=TRUE>>=

library(pod)
data(simEset)

@

Using our \texttt{simExprst} ExpressionSet object, we can now compute our outlier statistics, for instance the outlying degree, Zscore and Rscore as below.


<<>>=

norm.out.deg <- outlyingDegree(simEset), k=5)

norm.out.deg[1:5,1:5]

norm.zscore <- zScore(simEset), robust=FALSE)

norm.zscore[1:5,1:5]

norm.rscore <- zScore(simEset), robust=TRUE)

norm.rscore[1:5,1:5]

@

Similarly, we can compute these values using a plain matrix.

<<>>=

norm.exprs <- exprs(simEset))

norm.out.deg.mat <- outlyingDegree(norm.exprs, k=5)

all.equal(norm.out.deg, norm.out.deg.mat)

@

<<>>=

<<eval=TRUE, echo=FALSE>>=

cite.lines <- c('@article{bottomly2013,',
  'title={Comparison of methods to identify aberrant expression patterns in individual patients: augmenting our toolkit for precision medicine},',
  'author={Bottomly, Daniel and Ryabinin, Peter A and Tyner, Jeffrey W and Chang, Bill H and Loriaux, Marc M and Druker, Brian J and McWeeney, Shannon K and Wilmot, Beth},',
  'journal={Genome medicine},',
  'volume={5},',
  'number={11},',
  'pages={103},',
  'year={2013},',
  'publisher={BioMed Central Ltd}',
'}')

writeLines(cite.lines, con="pod.bib")

@

\section{Acknowledgements}

The implementation of the outlying degree and the simulation functions was based on the work of Peter Ryaninbin when he was part of our lab.  We also thank Heather Turner for her helpful suggestions on the vignette and package in general.

\bibliographystyle{plainnat}
\bibliography{pod}

<<>>=

sessionInfo()
@

\end{document}
